### ISSUE TITLE
Requires Rtools v.3.1?

### ISSUE THREAD

**Issue by DataStrategist** [rstudio/rstudioaddins#3]
I tried installing the addins examples, using your command: 
`devtools::install_github("rstudio/addinexamples", type = "source")`

... and got the error message:
`WARNING: Rtools 3.3 found on the path at C:/RBUILD~1/3.3 is not compatible with R 3.2.2.`

`Please download and install Rtools 3.1 from http://cran.r-project.org/bin/windows/Rtools/, remove the incompatible version from your PATH, then run find_rtools().`

Is it normal that you should require v.3.1?

**Comment by kevinushey** [comment]
Is this an error emitted by RStudio or `devtools`? (Do you see the same error if you try to run the R console?) Likely a fix will have to come in one of those packages.

You might want to just install Rtools 3.2 for now (Rtools 3.3 is somewhat experimental / in flux at the moment).

**Comment by DataStrategist** [comment]
it must be devtools, tried running from 3.2.2 x64 and got the same message. Will install Rtools 3.2 and will add an update

**Comment by DataStrategist** [comment]
Yeah, that fixed it. My steps: Install RTools 3.2, restart RStudio, try to install, success! Shall I close?
