### ISSUE TITLE
Addins configuration for rstudio-server and apache?

### ISSUE THREAD

**Issue by mbacou** [rstudio/rstudioaddins#4]
I'm trying to use the new addins with RStudio Server (on my own dedicated host proxied through apache). Problem is they try to spawn local browser windows at http://127.0.0.1 and that fails as I'm not running RStudio locally. 
Do I need to add rules to my apache vhost configuration to make this work?
Thanks.

```
> rhandsontable:::editAddin()
Loading required package: shiny
Listening on http://127.0.0.1:3883
> addinslist:::addinslistAddin()
Listening on http://127.0.0.1:3883
```

**Comment by kevinushey** [comment]
You might be able to handle this by setting the `shiny.host` R option, e.g. something like:

```R
options(shiny.host = "/path/to/RStudio/")
addinslist:::addinslistAddin()
```

Does that help here?

**Comment by mbacou** [comment]
Thanks, this now tries to launch a new windows at:
```
 > addinslist:::addinslistAddin()
Listening on http://rstudio.harvestchoice.org:3556`
```
Can I specify a port number as well?

Also where's the best place to save these options so it works globally for all users?

**Comment by ignacio82** [comment]
I have exaclty the same problem. Is is possible to set the port so I can use addins with rstudio server?

**Comment by jjallaire** [comment]
This should already work via localhost proxying (whenever a localhost URL is created RStudio will proxy it using e.g. http://mydomain.net/p/4536/). It's possible you just need to configure your proxy server so it handles all of the traffic as expected. Docs on running behind a proxy are here: https://support.rstudio.com/hc/en-us/articles/200552326-Running-RStudio-Server-with-a-Proxy
